### PR TITLE
Contact form

### PR DESCRIPTION
**Pull request by mesfin345**
- Corrected some text errors

### CODE REVIEW

**Comment by mesfin345** [comment]
My partner and mine portfolio design are different, and we are act as a navigator for others during contact form implementations.

**Review by Debas-31 — CHANGES_REQUESTED** [review]
> ## Hi team,
# Status: Require Change :negative_squared_cross_mark: :negative_squared_cross_mark: :negative_squared_cross_mark: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project that is supposed to be worked on by you and your partner(s), but only your commit can be found on the commit history.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mesfin345** [comment]
- this project is my 3rd time can you please understand me- this project is my 3rd time can you please understand me
- 
> > ## Hi team,
> 
> # Status: Require Change ❎ ❎ ❎
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> * [ ]  You have submitted a project that is supposed to be worked on by you and your partner(s), but only your commit can be found on the commit history.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mesfin345** [comment]
- can you please approve me this is my 3rd time repeating this module

**Comment by mesfin345** [comment]
- and also my coding partner also got approved without collaborating with me

**Review by mckent05 — APPROVED** [review]
Hi @mesfin345,

# STATUS : APPROVED ✔️ ✔️  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- All linter checks are passing ✔️ 
-  Contact form is working as expected 👍 👍 
- GitHub flow was correctly followed 👏 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
